[package]
name = "tray-play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tray-item = "0.7.1"
rodio = "0.16.0"
dirs = "4.0.0"

[build-dependencies]
windres = "0.2.2"
